extends TextureRect

func _ready() -> void:
	$VBoxContainer/Btn_NewGame.grab_focus()
	global.set_music(load("res://music/area_0.ogg"))
	await global.fade_in()


func _process(_delta: float) -> void:
	if Input.is_action_just_pressed("ui_cancel"):
		$VBoxContainer/Btn_Quit.emit_signal("pressed")


func _on_btn_new_game_pressed():
	var scene = load("res://menus/new_game_menu.tscn")
	global.goto_scene(scene)


func _on_btn_continue_pressed():
	var scene = load("res://menus/continue_game_menu.tscn")
	global.goto_scene(scene)


func _on_btn_options_pressed():
	var scene = load("res://menus/options_menu.tscn")
	global.goto_scene(scene)


func _on_btn_quit_pressed():
	await global.fade_out()
	get_tree().quit()
