extends Node2D

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	global.set_music(load("res://music/area_1.ogg"))
	if !global.player:
		global.player = load("res://objects/player.tscn").instantiate()
		global.player.position = $PlayerSpawn.position
		get_tree().root.add_child.call_deferred(global.player)
	if global.player && global.player_target:
		global.player.position = global.offset + get_node(global.player_target).position
		print("setting player location: ", global.player.position)
	await global.fade_in()


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(_delta: float) -> void:
	pass
